# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bag.proto
# Protobuf Python Version: 5.26.0-rc3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tbag.proto\x12\x03\x62\x61g\"D\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\"4\n\nBagRequest\x12\x18\n\x05items\x18\x01 \x03(\x0b\x32\t.bag.Item\x12\x0c\n\x04size\x18\x02 \x01(\x05\"\r\n\x0b\x42\x61gResponse')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEM']._serialized_start=18
  _globals['_ITEM']._serialized_end=86
  _globals['_BAGREQUEST']._serialized_start=88
  _globals['_BAGREQUEST']._serialized_end=140
  _globals['_BAGRESPONSE']._serialized_start=142
  _globals['_BAGRESPONSE']._serialized_end=155
# @@protoc_insertion_point(module_scope)
